anjoValue = "Viih Tube"

liderValue = "o Arthur"

monstroArray = ["Rodolffo", "Arthur"]

paredaoArray = ["Rodolffo", "Carla", "Fiuk"]

elenco = [
    ['o Arthur', 'https://uploads.metropoles.com/wp-content/uploads/2021/03/02145955/arthur_bbb21-600x400.jpg'],
    ['a Karol Conká', 'https://files.nsctotal.com.br/s3fs-public/styles/paragraph_image_style/public/graphql-upload-files/karol-konka-eliminacao-bbb21-memes_0.jpg?EFEb33qeZ8iRiRghdSmDc3pwGh8QSLgS&itok=nAsm3yub'],
    ['o Caio', 'https://www.emaisgoias.com.br/wp-content/uploads/2021/02/bbb-21-caio-inova-no-visual-1612489030988_v2_1910x1073-960x640.jpg'],
    ['a Carla Diaz', 'https://caras.uol.com.br/images/large/2021/02/16/carla-diaz-desabafa-apos-desentendimento-com-lumena-961442.jpg'],
    ['o João Luiz', 'https://stc.ofuxico.com.br/img/upload/noticias/2021/02/03/joao-luiz-falando-de-lucas-penteado-quarto-do-lider-bbb21_395540_36.jpg'],
    ['a Camilla de Lucas',
     'https://popnow.com.br/wp-content/uploads/2021/02/Eu4HuZXXAAYcyAv-1000x563.jpg'],
    ['o Arcrebiano', 'https://noticiasdatv.uol.com.br/media/uploads/artigos/arcrebiano-reproducao-bbb-globoplay.jpg'],
    ['a Pocah', 'https://odia.ig.com.br/_midias/jpg/2021/02/01/1200x750/1_pocah-21089949.jpg'],
    ['a Juliette', 'https://conteudo.imguol.com.br/c/entretenimento/54/2021/02/01/juliette-no-bbb-21-1612225746542_v2_450x337.png'],
    ['o Nego Di', 'https://media.tenor.com/images/d14795e193d89210da611771639c7d27/tenor.png'],
    ['a Kerline', 'https://catracalivre.com.br/wp-content/thumbnails/GIRdKc1Hs7dx_3ljTdMsfdm5CN8=/wp-content/uploads/2021/01/kerline-1-450x281.jpg'],
    ['o Lucas Penteado', 'https://stc.ofuxico.com.br/img/upload/noticias/2021/01/29/penteado-capa_395183_36.jpg'],
    ['a Lumena', 'https://catracalivre.com.br/wp-content/uploads/2021/02/lumena.jpg'],
    ['o Rodolffo', 'https://www.memesdavida.com.br/wp-content/uploads/2021/02/3516294-rodolffo-do-bbb21-tem-nude-exposto-e-950x600-1-730x450.jpg'],
    ['o Gilberto', 'https://portalpopline.com.br/wp-content/uploads/2021/02/Gilberto-1.jpg'],
    ['a Viih Tube', 'https://static1.purepeople.com.br/articles/5/31/29/15/@/3535998--bbb-21-viih-tube-revela-ter-ficado-2-624x600-1.jpg'],
    ['a Thaís', 'https://s2.glbimg.com/u9Tgd-sFNLJXag8OTKap7M4Q6d4=/682x43:1238x1037/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_e84042ef78cb4708aeebdf1c68c6cbd6/internal_photos/bs/2021/S/3/I5XA9KSsuASGUwqDtVmw/bbb21-010321-232026.jpg'],
    ['o Projota', 'https://www.tenhomaisdiscosqueamigos.com/wp-content/uploads/2021/03/Projota-no-BBB-21.jpg'],
    ['a Sarah', 'https://portalpopline.com.br/wp-content/uploads/2021/02/sarah-2.jpg'],
    ['o Fiuk', 'https://i.uai.com.br/P_l_gjUADe5tZQdBYdEyoqrbyU0=/750x0/imgsapp2.uai.com.br/app/noticia_133890394703/2021/02/09/267978/20210209155556304004e.jpeg']
]

quoteArray = [
    "Você está no paredão! 🧱",
    "Você está imune! 👼",
    "Você recebeu R$ 50.000 na sua carteira do PicPay 💲",
    "Indique 2 pessoas ao paredão 😈",
    "TOP 10 aprensentadores de BBB: Eu 😎",
    "Escolha uma música para o Gil cantar 🎵",
    "Indique 3 pessoas para irem ao paredão com você 😈",
    "Rodolffo diz: Arrebentando arame, rasteira baiana, engrenagem enpenando. Bicicleta perdendo freio na descida, vaca entrando no meio de roça!, moto fazendo tananananannann 🤠",
    "Imunize 1 pessoa 👼",
    "Tiago Leifert, você é a vergonha da profisson! 🤬",
    "Se querer é poder, você pode passar em cálculo! 🤯",
    "O Fiuk brigou com você por comida. Fique em silêncio por 1 minuto 🤫",
    "Você tem o poder de descobrir o voto de alguém no último paredão. Pra quem gostaria de perguntar? 😯",
    "Você aceita um prato de Strogonoff? O Projota não quis o dele 🥘",
    "Você ressignificou a conversa com inverdades e menosprezou a jornada da Lumena 😭",
    "Eu sou melhor que o Tiago Leifert 😘",
    "Agostinho Bot Carrara está chegando. Eu avisei! 🚨",
    "Não quero mais te ver hoje - CONKÁ, Karol (ou seria o Jacquin?) 🤮",
    "Você está no paredão falso! 🤐",
    "O ICMC é melhor que o PROJAC 😎",
    "Abaixa o som da TV e me escuta pelo telefone! 📞",
    "Eu e Mendonça comandamos a repartição virtual quando Lineuzinho está de folga 🤫",
    "Indique 3 pessoas ao paredão 😈",
    "O Nego Di fez uma piada. Sorria por 3 horas 😁",
    "PYONG LEEEEEEEEE ⛩",
    "Cuidado, Lineuzinho! O Beiçola está dançando com a Nenê 🐂",
    "Que tal atuar um pouco? Você está na nova novela das 21h! 🎬",
    "Indique 2 pessoas para irem ao paredão falso com você! 🤐",
    "Indique 1 pessoa para ganhar uma viagem para a Lua 🌑",
    "Palmeiras não tem mundial 🐷",
    "Indique 1 pessoa ao paredão 😈",
    "Vem ser feliz aqui fora! Você está eliminadx 🚫",
    "Você é o novo líder! 👑",
    "Há um novo integrante no mundo dos bots: Agostinho Bot Carrara 🤪",
    "Você ganhou uma palestrinha da Juliette 🙉",
    "Planta faz isso? 💃 🌱",
    "Você ganhou 3 ingressos para o show do Fiuk 🎸",
    "Você está fora do BBB e foi indicado diretamente para A Fazenda 🐴",
    "Indique 2 pessoas para o monstro 👹",
    "Você ganhou um bolo de chocolate do Fiuk 🎂",
    "Indique 3 pessoas para o Quarto Branco ⬜",
    "Agora você segue a Viih Tube 😾",
    "O Boninho gostou de você! Agora vai substituir a Fátima Bernardes 👩",
    "Indique 1 pessoa para ir ao Quarto Branco com você ⬜",
    "Você ganhou 1 ano grátis no Méqui 🍔",
    "Você ganhou 2 ingressos para o show do Projota 🎤",
    "Escolha: 5 dias no quarto branco ou 1 hora com o Projota? 🤔",
    "JOGA Y JOGA - Você está na final do BBB! 🤑",
    "Você ganhou um sono da beleza com a Pocah 😴",
    "Você ganhou 4 ingressos para o show da Pocah 🎇",
    "Tiago Leifert era melhor narrando FIFA (mentira, nem nisso) 😒",
    "Você recebeu R$ 100.000 na sua carteira do PicPay 💲",
    "A Karol Conká se declarou pra você no Instagram. Está canceladx! 🚫",
    "Você ganhou uma viagem para a vila do Projota muleque de vila kk 🏙",
    "Você ganhou um patinete da Americanas 🛴",
    "Você agora é a Carla Diaz. Peça alguém em casamento 💍",
    "Você ganhou uma ligação para o Rafael Portugal 📞",
    "A Sarah disse que era sua amiga, mas era mentira. Fique em silêncio por 2 minutos 😫",
    "Você ganhou um tênis da Americanas 👟",
    "Tiago Leifert nunca chegará aos meus pés 😎",
    "A casa de vidro voltou e a Ivy vai dormir no seu quarto 🤣",
    "Eu sou Pedro Bot Bial e nasci em 2021 🤖",
    "Você ganhou um banho grátis! (a Viih Tube não quis) 🚿",
    "Você ganhou uma aula de crossfit com o Arhur! Aulas, Cria 🏋️‍♀️",
    "Minx, seus cabelo é daora 🎶",
    "Você ganhou um Galaxy S21 da Americanas 📱",
    "MUSICAS FODA: https://youtu.be/WUg-ADJg-H0",
    "Eu sou bem melhor que o Jô Soares 😛",
    "Você ganhou o direito de saber o que está acontecendo aqui fora. O que gostaria de perguntar? 🧐",
    "Você está no Arquivo Confidencial! 💾",
    "Agora você segue a Karol Conká ☣",
    "Você ganhou a nova Fiat Toro 🐂",
    "EU AÍ KKK: https://youtu.be/ZJiCYajcpq8 ",
    "Você ganhou um feat com o Lucas Penteado 🎤",
    "Você ganhou um Fiat Uno 🚗",
    "Prazer, meu nome é Pedro Bot Bial 😂",
    "PARA DE GRITAAAAAAAA 😱",
    "Você ganhou um café da manhã com a Ana Maria Braga! Parabéns, está eliminadx! 🚫",
    "Você ganhou um corte de cabelo da Avon ✂",
    "No mundo dos bots, eu sou o melhor amigo do Lineuzinho ❤",
    "Você ganhou 5 ingressos para o show da Karol Conká 🎙",
    "Você ganhou um esmalte da Avon 💅",
    "Você fez a Kerline chorar. Fique 1 minuto em silêncio 😭",
    "O Gil está indignado com você! Fique em silêncio por 10 minutos 🤫",
    "Você está no VIP! 🌟",
    "Após o sinal, diga o seu nome e a cidade de onde está falando 😅",
    "Você está na Xepa! 🤭",
    "Falem bem ou falem mal, eu fui o melhor que vocês já tiveram. Bj no ombro, Tiago Leifert 😗",
    "Você está eliminadx! 🚫",
    "Indique uma pessoa para fazer recuperação com você 🥺"
]
