quoteArray = [
              "Você está no paredão! 🧱", 
              "Você está imune! 👼", 
              "Você recebeu R$ 50.000 na sua carteira do PicPay 💲",
              "Indique 2 pessoas ao paredão 😈",     
              "Imunize 1 pessoa 👼",
              "Imunize 2 pessoas 👼",
              "Você está no paredão falso! 🤐",
              "Indique 3 pessoas ao paredão 😈",
              "Indique 2 pessoas para irem ao paredão falso com você! 🤐",
              "Palmeiras não tem mundial 🐷",
              "Indique 1 pessoa ao paredão 😈",
              "Eu sou melhor que o Tiago Leifert 😘",
              "Vem ser feliz aqui fora! Você está eliminadx 🚫",
              "Você é o novo líder! 👑",
              "Você ganhou 3 ingressos para o show do Fiuk 🎸",
              "Indique 2 pessoas para o monstro 👹",
              "Você recebeu R$ 0 na sua carteira do PicPay 💲",
              "Indique 3 pessoas para o Quarto Branco ⬜",
              "Agora você segue a Viih Tube 😾",
              "Indique 1 pessoa para ir ao Quarto Branco com você ⬜",
              "Você ganhou 1 ano grátis no Méqui 🍔",
              "Você ganhou 2 ingressos para o show do Projota 🎤",
              "Você recebeu R$ 5.000 na sua carteira do PicPay 💲",
              "Você recebeu R$ 1 na sua carteira do PicPay 💲",
              "Você ganhou 4 ingressos para o show da Pocah 🎇",
              "Você recebeu R$ 100.000 na sua carteira do PicPay 💲",
              "Você ganhou uma TV 4k 60' Samsung da Americanas 📺",
              "Você ganhou um patinete da Americanas 🛴",
              "Você ganhou uma bicicleta da Americanas 🚲",
              "Você ganhou um tênis da Americanas 👟",
              "Você ganhou um PS5 da Americanas 🎮",
              "Você ganhou um chuveiro da Americanas 🚿",
              "Você ganhou um Galaxy S21 da Americanas 📱",
              "Você ganhou a nova Fiat Toro 🐂",
              "Você recebeu R$ 10.000 na sua carteira do PicPay 💲",
              "Você ganhou um Fiat Uno 🚗",
              "Você ganhou um corte de cabelo da Avon ✂",
              "Você ganhou 5 ingressos para o show da Karol Conká 🎙",
              "Você ganhou um esmalte da Avon 💅",
              "Você está no VIP! 🌟",
              "Você está na Xepa! 🤭",
              "Você está eliminadx! 🚫",
              "Você ganhou um Fiat Palio 🚙"
            ]
